import Banner from '@/components/ui/Banner'
import Header from '@/components/ui/Header'
import { CartContextProvider } from '@/contexts/CartContext'
import '@/style/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartContextProvider>
          <div className="bg-white relative">
            <Banner />
            <Header />
            {children}
          </div>
        </CartContextProvider>
      </body>
    </html>
  )
}
