import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/style/globals.css'
import Header from '../_UI/Header'
import Banner from '../_UI/Banner'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-white relative">
          <Banner />
          <Header />
          {children}
        </div>
      </body>
    </html>
  )
}
